### ISSUE TITLE
Watcher plugin API

### ISSUE THREAD

**Issue by ide** [amasad/sane#54]
Branching off the discussion about the chokidar watcher in #53, I've been thinking that a plugin API could be useful to let users of sane (e.g. me) use custom watchers without bloating the sane package or adding too much maintenance cost. 

My end goal is to be able to use a custom watcher with the RN packager where the pieces are layered like this:

<img src="http://i.imgur.com/B8cBxlq.jpg" />

(The packager would also expose a flag to set the watcher implementation.)

At a high level is this something you'd be open to?

**Comment by amasad** [comment]
yes!

**Comment by amasad** [comment]
It's worth looking into the NodeWatcher again with iojs. It might be good enough now without any native extensions. I remember seeing a few patches on libuv for better watching (and less fsevents bugs)

**Comment by ide** [comment]
Nice to hear that. Will be able to test it on a moderately sized project once react-native's dependencies have been updated to support io.js 3.x.

**Comment by ide** [comment]
Didn't investigate deeply but did run into "too many open files" after uninstalling watchman:
```
Error: EMFILE: too many open files, open '/Users/ide/.babel.json'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:549:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1155:15)
    at process.save (/Users/ide/.nvm/versions/io.js/v3.2.0/lib/node_modules/exp/node_modules/react-native/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process.exit (node.js:737:17)
    at process.<anonymous> (/Users/ide/.nvm/versions/io.js/v3.2.0/lib/node_modules/exp/node_modules/react-native/packager/packager.js:156:11)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
```

The packager works fine with watchman or chokidar though.

**Comment by ccheever** [comment]
As a start for a proposal: 
- watcher plugins would be published as a separate npm package, typically prefixed with `sane-`
  - For example, I would publish the chokidar watcher as `sane-chokidar` or `sane-chokidar`
  - Plugins would list `sane` as a peer depency. `sane` itself would not list any plugins.
  - To use a custom watcher via a plugin, the function `sane(dir, opts)` would be updated to allow an optin called `watcher` which you would pass an instance of a class that implements the same interface that `PollWatcher` and `watchman_watcher` use.

For a concrete example, this is how you would use the ChokidarWatcher.
```js
    ...
    let cw = new require('sane-chokidar');
    let w = sane('.', {watcher: cw});
    ...
```

**Comment by amasad** [comment]
As mentioned on the PR. This is fine by me, but I'm missing the point of this if `sane` would just return the argument passed. If you gave me an example of how this would be used in the wild maybe I'll have a better understanding
