### ISSUE TITLE
`sane@1.3.3` fails` npm shrinkwrap`

### ISSUE THREAD

**Issue by sterpe** [amasad/sane#63]
Seems like trying to shrink-wrap dependencies when sane is included in the project fails in `npm@3` with this error message:

```
 $ npm shrinkwrap --dev
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/sterpe/.nvm/versions/node/v4.3.2/bin/node" "/Users/sterpe/git/Video/vpaid/.node_modules/.bin/npm" "shrinkwrap" "--dev"
npm ERR! node v4.3.2
npm ERR! npm  v3.8.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: watch@~0.10.0, required by sane@1.3.3
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sterpe/git/Video/vpaid/npm-debug.log
```

**Comment by sterpe** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/sterpe/.nvm/versions/node/v4.3.2/bin/node',
1 verbose cli   '/Users/sterpe/git/Video/vpaid/.node_modules/.bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@3.8.1
3 info using node@v4.3.2
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack missing: watch@~0.10.0, required by sane@1.3.3
4 verbose stack     at shrinkwrap_ (/Users/sterpe/git/Video/vpaid/.node_modules/npm/lib/shrinkwrap.js:101:15)
4 verbose stack     at /Users/sterpe/git/Video/vpaid/.node_modules/npm/lib/shrinkwrap.js:36:5
4 verbose stack     at /Users/sterpe/git/Video/vpaid/.node_modules/npm/node_modules/iferr/index.js:13:50
4 verbose stack     at /Users/sterpe/git/Video/vpaid/.node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/Users/sterpe/git/Video/vpaid/.node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/sterpe/git/Video/vpaid/.node_modules/npm/node_modules/slide/lib/chain.js:18:7
4 verbose stack     at cb (/Users/sterpe/git/Video/vpaid/.node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/sterpe/git/Video/vpaid/.node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/Users/sterpe/git/Video/vpaid/.node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/sterpe/git/Video/vpaid/.node_modules/npm/node_modules/slide/lib/chain.js:18:7
5 verbose cwd /Users/sterpe/git/Video/vpaid
6 error Darwin 15.3.0
7 error argv "/Users/sterpe/.nvm/versions/node/v4.3.2/bin/node" "/Users/sterpe/git/Video/vpaid/.node_modules/.bin/npm" "shrinkwrap" "--dev"
8 error node v4.3.2
9 error npm  v3.8.1
10 error Problems were encountered
10 error Please correct and try again.
10 error missing: watch@~0.10.0, required by sane@1.3.3
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by sterpe** [comment]
Maybe something to do with npm3 ?

**Comment by amasad** [comment]
Pretty sure there are plenty of projects using shrinkwrap with sane. See react-native for example: https://github.com/facebook/react-native/blob/e6343a83e240c71b23ed4f292e62fa8c0ab3e181/npm-shrinkwrap.json#L4944

I suggest deleting your existing shrinkwrap, node_modules, do a fresh install and then shrinkwrap

**Comment by sterpe** [comment]
Yeah.  I will investigate further.  Maybe the tree npm is producing is corrupted somehow....Thanks.

**Comment by sterpe** [comment]
@amasad It appears that `npm3` is corrupting the tree due to the presence of `watch@0.17.x` in the project's root `package.json` and not installing `watch@0.10.x` for `sane`
